#!/bin/bash

#TIME=`date +'%Y':'%H:%M'`
#TIME2=`date -d "-1 min" +'%Y':'%H:%M'`

while :
do
cat /usr/local/nginx/logs/access.log  | awk '{print $1 "," substr($4,14,5)}' | uniq -c | awk '{print $2 "," $1}' > /tmp/nginx_list

MAXCOUNT="300"
 
for i in `cat /tmp/nginx_list`
do
    IP=`echo $i | awk -F, '{print $1}'`
    NUM=`echo $i | awk -F, '{print $3}'`
 
if [ $NUM -gt $MAXCOUNT ];then
 
   grep $IP /usr/local/nginx/conf/nginx_deny.conf > /dev/null
   if [ $? -gt 0 ];then
	echo "deny  $IP;" >> /usr/local/nginx/conf/nginx_deny.conf
   fi
fi 
done
sleep 60
done
